<?php


namespace Coff\OandaWrapper\Endpoint;


use Psr\Http\Message\ResponseInterface;

class AccountsEndpoint extends Endpoint
{
    private $path = '/accounts';

    public function getPath()
    {
        return parent::getPath() . $this->path; // TODO: Change the autogenerated stub
    }

    public function getMethod()
    {
        return self::METHOD_GET;
    }

    public function parseResponse(ResponseInterface $response)
    {
        $stream = $response->getBody();

        $this->result = json_decode($stream->getContents());
    }

}