<?php


namespace Coff\OandaWrapper\Endpoint;


class AccountsEndpoint extends Endpoint
{
    private $path = '/accounts';

    public function getPath()
    {
        return parent::getPath() . $this->path; // TODO: Change the autogenerated stub
    }

    public function getMethod()
    {
        return self::METHOD_GET;
    }
}