<?php


namespace Coff\OandaWrapper\Endpoint;


class InstrumentsEndpoint extends Endpoint
{
    private $path = '/instruments';

    public function getPath()
    {
        return parent::getPath() . $this->path; // TODO: Change the autogenerated stub
    }

}